<div class="block block-new-customer">
    <div class="block-title">
        <strong id="block-new-customer-heading" role="heading" aria-level="2">Customer Registration is Temporarily disaled</strong>
    </div>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <p>The new account registration is disabled. Please contact Admin for assistence</p>
    </div>
</div>
